[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
line_length = 88
profile = "black"

[flake8]
# E203: ignored because this causes conflict with `black`. Ref: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices
# W503: ignored because this rule goes against PEP8. Ref: https://www.flake8rules.com/rules/W503.html
max-line-length = 88
extend-ignore = ['D100', 'D104', 'D401', 'E203', 'W503']
docstring-convention="numpy"

[tool.mypy]
python_version = "3.9"
no_implicit_optional = true
ignore_missing_imports = true
check_untyped_defs = true
disallow_untyped_defs = true
warn_unused_ignores = true
exclude = ['tests',]

[tool.pytest.ini_options]
testpaths = ["tests",]
filterwarnings = ["ignore::DeprecationWarning",]

[tool.pyright]
include = ["module"]
exclude = [
    "tests",
    "**/node_modules",
    "**/__pycache__"
]
reportMIssingImports = true
pythonVersion = "3.8.6"
stubPath = ""
pythonPlatform = "Linux"
extraPaths = [
    "./src",
    "./module",
    "./modules",
]
typeCheckingMode = "off"  # use mypy for type checking
useLibraryCodeForTypes = false
